// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: client/v1/tx_notification.proto

package clientv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on TxCheckServiceCheckRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TxCheckServiceCheckRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TxCheckServiceCheckRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TxCheckServiceCheckRequestMultiError, or nil if none found.
func (m *TxCheckServiceCheckRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TxCheckServiceCheckRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Key

	if len(errors) > 0 {
		return TxCheckServiceCheckRequestMultiError(errors)
	}

	return nil
}

// TxCheckServiceCheckRequestMultiError is an error wrapping multiple
// validation errors returned by TxCheckServiceCheckRequest.ValidateAll() if
// the designated constraints aren't met.
type TxCheckServiceCheckRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TxCheckServiceCheckRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TxCheckServiceCheckRequestMultiError) AllErrors() []error { return m }

// TxCheckServiceCheckRequestValidationError is the validation error returned
// by TxCheckServiceCheckRequest.Validate if the designated constraints aren't met.
type TxCheckServiceCheckRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TxCheckServiceCheckRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TxCheckServiceCheckRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TxCheckServiceCheckRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TxCheckServiceCheckRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TxCheckServiceCheckRequestValidationError) ErrorName() string {
	return "TxCheckServiceCheckRequestValidationError"
}

// Error satisfies the builtin error interface
func (e TxCheckServiceCheckRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTxCheckServiceCheckRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TxCheckServiceCheckRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TxCheckServiceCheckRequestValidationError{}

// Validate checks the field values on TxCheckServiceCheckResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *TxCheckServiceCheckResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TxCheckServiceCheckResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// TxCheckServiceCheckResponseMultiError, or nil if none found.
func (m *TxCheckServiceCheckResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *TxCheckServiceCheckResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return TxCheckServiceCheckResponseMultiError(errors)
	}

	return nil
}

// TxCheckServiceCheckResponseMultiError is an error wrapping multiple
// validation errors returned by TxCheckServiceCheckResponse.ValidateAll() if
// the designated constraints aren't met.
type TxCheckServiceCheckResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TxCheckServiceCheckResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TxCheckServiceCheckResponseMultiError) AllErrors() []error { return m }

// TxCheckServiceCheckResponseValidationError is the validation error returned
// by TxCheckServiceCheckResponse.Validate if the designated constraints
// aren't met.
type TxCheckServiceCheckResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TxCheckServiceCheckResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TxCheckServiceCheckResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TxCheckServiceCheckResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TxCheckServiceCheckResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TxCheckServiceCheckResponseValidationError) ErrorName() string {
	return "TxCheckServiceCheckResponseValidationError"
}

// Error satisfies the builtin error interface
func (e TxCheckServiceCheckResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTxCheckServiceCheckResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TxCheckServiceCheckResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TxCheckServiceCheckResponseValidationError{}
